//
// Created by ENDERZOMBI102 on 26/10/2023.
//
#include "inputmaps.hpp"


std::array<ButtonMapEntry, 113> BUTTON_MAP{{
	// KEYBOARD
	{ .name="0", .code=ButtonCode_t::KEY_0 },
	{ .name="1", .code=ButtonCode_t::KEY_1 },
	{ .name="2", .code=ButtonCode_t::KEY_2 },
	{ .name="3", .code=ButtonCode_t::KEY_3 },
	{ .name="4", .code=ButtonCode_t::KEY_4 },
	{ .name="5", .code=ButtonCode_t::KEY_5 },
	{ .name="6", .code=ButtonCode_t::KEY_6 },
	{ .name="7", .code=ButtonCode_t::KEY_7 },
	{ .name="8", .code=ButtonCode_t::KEY_8 },
	{ .name="9", .code=ButtonCode_t::KEY_9 },
	{ .name="a", .code=ButtonCode_t::KEY_A },
	{ .name="b", .code=ButtonCode_t::KEY_B },
	{ .name="c", .code=ButtonCode_t::KEY_C },
	{ .name="d", .code=ButtonCode_t::KEY_D },
	{ .name="e", .code=ButtonCode_t::KEY_E },
	{ .name="f", .code=ButtonCode_t::KEY_F },
	{ .name="g", .code=ButtonCode_t::KEY_G },
	{ .name="h", .code=ButtonCode_t::KEY_H },
	{ .name="i", .code=ButtonCode_t::KEY_I },
	{ .name="j", .code=ButtonCode_t::KEY_J },
	{ .name="k", .code=ButtonCode_t::KEY_K },
	{ .name="l", .code=ButtonCode_t::KEY_L },
	{ .name="m", .code=ButtonCode_t::KEY_M },
	{ .name="n", .code=ButtonCode_t::KEY_N },
	{ .name="o", .code=ButtonCode_t::KEY_O },
	{ .name="p", .code=ButtonCode_t::KEY_P },
	{ .name="q", .code=ButtonCode_t::KEY_Q },
	{ .name="r", .code=ButtonCode_t::KEY_R },
	{ .name="s", .code=ButtonCode_t::KEY_S },
	{ .name="t", .code=ButtonCode_t::KEY_T },
	{ .name="u", .code=ButtonCode_t::KEY_U },
	{ .name="v", .code=ButtonCode_t::KEY_V },
	{ .name="w", .code=ButtonCode_t::KEY_W },
	{ .name="x", .code=ButtonCode_t::KEY_X },
	{ .name="y", .code=ButtonCode_t::KEY_Y },
	{ .name="z", .code=ButtonCode_t::KEY_Z },
	{ .name="PAD_0", .code=ButtonCode_t::KEY_PAD_0 },
	{ .name="PAD_1", .code=ButtonCode_t::KEY_PAD_1 },
	{ .name="PAD_2", .code=ButtonCode_t::KEY_PAD_2 },
	{ .name="PAD_3", .code=ButtonCode_t::KEY_PAD_3 },
	{ .name="PAD_4", .code=ButtonCode_t::KEY_PAD_4 },
	{ .name="PAD_5", .code=ButtonCode_t::KEY_PAD_5 },
	{ .name="PAD_6", .code=ButtonCode_t::KEY_PAD_6 },
	{ .name="PAD_7", .code=ButtonCode_t::KEY_PAD_7 },
	{ .name="PAD_8", .code=ButtonCode_t::KEY_PAD_8 },
	{ .name="PAD_9", .code=ButtonCode_t::KEY_PAD_9 },
	{ .name="/", .code=ButtonCode_t::KEY_PAD_DIVIDE },
	{ .name="*", .code=ButtonCode_t::KEY_PAD_MULTIPLY },
	{ .name="-", .code=ButtonCode_t::KEY_PAD_MINUS },
	{ .name="+", .code=ButtonCode_t::KEY_PAD_PLUS },
	{ .name="PAD_ENTER", .code=ButtonCode_t::KEY_PAD_ENTER },
	{ .name="PAD_DECIMAL", .code=ButtonCode_t::KEY_PAD_DECIMAL },
	{ .name="[", .code=ButtonCode_t::KEY_LBRACKET },
	{ .name="]", .code=ButtonCode_t::KEY_RBRACKET },
	{ .name=";", .code=ButtonCode_t::KEY_SEMICOLON },
	{ .name="'", .code=ButtonCode_t::KEY_APOSTROPHE },
	{ .name="`", .code=ButtonCode_t::KEY_BACKQUOTE },
	{ .name=",", .code=ButtonCode_t::KEY_COMMA },
	{ .name=".", .code=ButtonCode_t::KEY_PERIOD },
	{ .name="/", .code=ButtonCode_t::KEY_SLASH },
	{ .name="\\", .code=ButtonCode_t::KEY_BACKSLASH },
	{ .name="-", .code=ButtonCode_t::KEY_MINUS },
	{ .name="=", .code=ButtonCode_t::KEY_EQUAL },
	{ .name="ENTER", .code=ButtonCode_t::KEY_ENTER },
	{ .name="SPACE", .code=ButtonCode_t::KEY_SPACE },
	{ .name="BACKSPACE", .code=ButtonCode_t::KEY_BACKSPACE },
	{ .name="TAB", .code=ButtonCode_t::KEY_TAB },
	{ .name="CAPSLOCK", .code=ButtonCode_t::KEY_CAPSLOCK },
	{ .name="NUMLOCK", .code=ButtonCode_t::KEY_NUMLOCK },
	{ .name="ESCAPE", .code=ButtonCode_t::KEY_ESCAPE },
	{ .name="SCROLLLOCK", .code=ButtonCode_t::KEY_SCROLLLOCK },
	{ .name="INS", .code=ButtonCode_t::KEY_INSERT },
	{ .name="DELETE", .code=ButtonCode_t::KEY_DELETE },
	{ .name="HOME", .code=ButtonCode_t::KEY_HOME },
	{ .name="END", .code=ButtonCode_t::KEY_END },
	{ .name="PGUP", .code=ButtonCode_t::KEY_PAGEUP },
	{ .name="PGDN", .code=ButtonCode_t::KEY_PAGEDOWN },
	{ .name="BREAK", .code=ButtonCode_t::KEY_BREAK },
	{ .name="SHIFT", .code=ButtonCode_t::KEY_LSHIFT },
	{ .name="RSHIFT", .code=ButtonCode_t::KEY_RSHIFT },
	{ .name="ALT", .code=ButtonCode_t::KEY_LALT },
	{ .name="RALT", .code=ButtonCode_t::KEY_RALT },
	{ .name="CTRL", .code=ButtonCode_t::KEY_LCONTROL },
	{ .name="RCTRL", .code=ButtonCode_t::KEY_RCONTROL },
	{ .name="LWIN", .code=ButtonCode_t::KEY_LWIN },
	{ .name="RWIN", .code=ButtonCode_t::KEY_RWIN },
	{ .name="APP", .code=ButtonCode_t::KEY_APP },
	{ .name="UPARROW", .code=ButtonCode_t::KEY_UP },
	{ .name="LEFTARROW", .code=ButtonCode_t::KEY_LEFT },
	{ .name="DOWNARROW", .code=ButtonCode_t::KEY_DOWN },
	{ .name="RIGHTARROW", .code=ButtonCode_t::KEY_RIGHT },
	{ .name="F1", .code=ButtonCode_t::KEY_F1 },
	{ .name="F2", .code=ButtonCode_t::KEY_F2 },
	{ .name="F3", .code=ButtonCode_t::KEY_F3 },
	{ .name="F4", .code=ButtonCode_t::KEY_F4 },
	{ .name="F5", .code=ButtonCode_t::KEY_F5 },
	{ .name="F6", .code=ButtonCode_t::KEY_F6 },
	{ .name="F7", .code=ButtonCode_t::KEY_F7 },
	{ .name="F8", .code=ButtonCode_t::KEY_F8 },
	{ .name="F9", .code=ButtonCode_t::KEY_F9 },
	{ .name="F10", .code=ButtonCode_t::KEY_F10 },
	{ .name="F11", .code=ButtonCode_t::KEY_F11 },
	{ .name="F12", .code=ButtonCode_t::KEY_F12 },
	{ .name="CAPSLOCK", .code=ButtonCode_t::KEY_CAPSLOCKTOGGLE },
	{ .name="NUMLOCK", .code=ButtonCode_t::KEY_NUMLOCKTOGGLE },
	{ .name="SCROLLLOCK", .code=ButtonCode_t::KEY_SCROLLLOCKTOGGLE },
	// MOUSE
	{ .name="MOUSE1", .code=ButtonCode_t::MOUSE_LEFT },
	{ .name="MOUSE2", .code=ButtonCode_t::MOUSE_RIGHT },
	{ .name="MOUSE3", .code=ButtonCode_t::MOUSE_MIDDLE },
	{ .name="MOUSE4", .code=ButtonCode_t::MOUSE_4 },
	{ .name="MOUSE5", .code=ButtonCode_t::MOUSE_5 },
	{ .name="MWHEELUP", .code=ButtonCode_t::MOUSE_WHEEL_UP },
	{ .name="MWHEELDOWN", .code=ButtonCode_t::MOUSE_WHEEL_DOWN },
}};


std::array<AnalogMapEntry, 4> ANALOG_MAP{{
	{ .name="MOUSE_X", .code=AnalogCode_t::MOUSE_X },
	{ .name="MOUSE_Y", .code=AnalogCode_t::MOUSE_Y },
	{ .name="MOUSE_XY", .code=AnalogCode_t::MOUSE_XY },
	{ .name="MOUSE_WHEEL", .code=AnalogCode_t::MOUSE_WHEEL },
}};